# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://samstandring.github.io/
title: Samantha Standring
email: ssmit038@ucr.edu
author: Samantha Standring
description: "Samantha Standring's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/samstandring 
  - icon: envelope-o
    title: email
    url: mailto:ssmit038@ucr.edu
#  - icon: linkedin
#    title: linkedin
#    url: https://www.linkedin.com/in/NyName/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/MyName

