# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://samstandring.github.io/
title: "Samantha Standring"
email: ssmit038@ucr.edu
author: Samantha Standring
description: "Samantha Standring's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/samstandring 
  - icon: envelope-o
    title: email
    url: mailto:ssmit038@ucr.edu
#  - icon: linkedin
#    title: linkedin
#    url: https://www.linkedin.com/in/NyName/
  - icon: file-pdf-o
    title: CV
    url: img/CV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/sam_standring
  - icon: google
    title: Google Scholar
    url: https://scholar.google.com/citations?hl=en&view_op=list_works&authuser=1&gmla=AJsN-F5laPWLRKvgdYNQbLBr8ESmVZACjmd2-CnImXfovoMkqKJaorym4EbMRHgwLw4EE-KpSFOxedNPYAcir2y2Zo7Ngl1M6gZp3YPUiNUBQLiYMFmjGt5h7NMDm7XAyHmNFaii1uPN&user=Ls2FMIkAAAAJ
